### ISSUE TITLE
What the 'BGW' means in the Demos?

### ISSUE THREAD

**Issue by BGI-COAD** [jumphone/FitDevo#1]
Hello! FitDevo author,
    I test the FitDevo recently, I am wondering the object named 'BGM' meaning. It looks like a gene name vector, and what the number means? Could you answer this question? Thanks!

**Comment by jumphone** [comment]
Hi, thanks for using FitDevo. 

Firstly, we learn the Gene Weight (GW) from a training dataset covering scRNA-seq data of 17 previously published datasets.

Please check the section named "The generation of GW" in our paper: https://doi.org/10.1093/bib/bbac293

Secondly, we get BGW by binarizing the GW.

if( GW>0 ){ BGW=1 }else{ BGW=0 } 

Best,
Feng Zhang
