### ISSUE TITLE
Lack of legend/scale showing what colors indicate

### ISSUE THREAD

**Issue by mcw83** [jumphone/FitDevo#3]
For FitDevo is there a legend that can be included with figures to indicated the meaning of the colors? I believe red is most undifferentiated and blue is predicted most differentiated, but it would be very helpful to have a labeled scale to show this. 
Thank you!

**Comment by jumphone** [comment]
@mcw83 

Hi, thanks for using FitDevo!

Please try the following code:
 
plot(x=FIELD$VALUE,y=rep(1,length(FIELD$VALUE)),col=FIELD$POINT.COL,type='h',lwd=2,ylim=c(0,1))

Best,
Feng
